export interface CareerPosition {
  slug: string;
  title: string;
  department: string;
  type: string;
  location: string;
  about: string;
  requirements: string[];
}

export const careers: CareerPosition[] = [
  {
    slug: 'web-developer',
    title: 'Web Developer',
    department: 'Technology',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We are looking for a skilled Web Developer to build fast, responsive, and conversion-focused websites. You will work with Next.js, React, WordPress, and Shopify to deliver production-grade web experiences for our clients.',
    requirements: [
      'Proficiency in HTML, CSS, JavaScript, and TypeScript',
      'Experience with React and Next.js or similar frameworks',
      'Working knowledge of WordPress and/or Shopify development',
      'Understanding of responsive design and Core Web Vitals',
      'Familiarity with Git version control',
      'Strong attention to detail and design sensibility',
      'Minimum 2 years of professional experience',
    ],
  },
  {
    slug: 'sr-graphic-designer',
    title: 'Senior Graphic Designer',
    department: 'Creative',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We need a Senior Graphic Designer who can lead visual direction across campaigns, brand identities, and digital assets. You will work closely with strategy and copy teams to produce work that is both beautiful and effective.',
    requirements: [
      'Expert proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)',
      'Strong portfolio demonstrating brand identity and campaign work',
      'Experience with motion graphics and video editing is a plus',
      'Understanding of digital design principles and responsive layouts',
      'Ability to lead junior designers and maintain design quality',
      'Minimum 4 years of professional design experience',
      'Agency experience preferred',
    ],
  },
  {
    slug: 'sr-copywriter',
    title: 'Senior Copywriter',
    department: 'Creative',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We are looking for a Senior Copywriter who can write compelling copy across brand strategy, digital campaigns, websites, and social media. You will shape brand voices and craft messages that move people to act.',
    requirements: [
      'Exceptional command of English with impeccable grammar',
      'Strong portfolio of brand, digital, and campaign copywriting',
      'Ability to write across tones — from corporate to conversational',
      'Experience with SEO copywriting and content strategy',
      'Understanding of digital marketing and consumer behaviour',
      'Minimum 4 years of copywriting experience',
      'Agency experience preferred',
    ],
  },
  {
    slug: 'business-development-manager',
    title: 'Business Development Manager',
    department: 'Growth',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We need a Business Development Manager to drive new client acquisition and revenue growth. You will identify opportunities, pitch our services, and build relationships with decision-makers across industries.',
    requirements: [
      'Proven track record in B2B sales or business development',
      'Understanding of digital marketing services and the agency landscape',
      'Excellent presentation and communication skills',
      'Ability to craft proposals and pitch decks independently',
      'CRM proficiency (HubSpot or Salesforce preferred)',
      'Minimum 3 years in business development or sales',
      'Existing network in marketing, real estate, BFSI, or D2C is a plus',
    ],
  },
  {
    slug: 'seo-specialist',
    title: 'SEO Specialist',
    department: 'Marketing',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We are hiring an SEO Specialist to drive organic growth for our clients through technical SEO, content optimisation, and link building. You will also explore AEO and GEO strategies for AI-powered search.',
    requirements: [
      'Strong understanding of on-page, off-page, and technical SEO',
      'Experience with SEO tools (Ahrefs, SEMrush, Screaming Frog, GA4)',
      'Knowledge of schema markup and structured data',
      'Understanding of Core Web Vitals and site performance',
      'Familiarity with AEO and GEO concepts is a plus',
      'Minimum 2 years of SEO experience',
      'Track record of ranking improvements and organic traffic growth',
    ],
  },
  {
    slug: 'performance-marketing-specialist',
    title: 'Performance Marketing Specialist',
    department: 'Marketing',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We are looking for a Performance Marketing Specialist to manage Meta Ads, Google Ads, and programmatic campaigns. You will own client ad accounts and be responsible for ROAS, CPA, and pipeline metrics.',
    requirements: [
      'Hands-on experience with Meta Ads Manager and Google Ads',
      'Understanding of attribution modelling and conversion tracking',
      'Experience with Google Analytics 4 and Tag Manager',
      'Ability to analyse campaign data and optimise for KPIs',
      'Experience with A/B testing and creative iteration',
      'Minimum 2 years in performance marketing',
      'Google Ads and Meta Blueprint certifications preferred',
    ],
  },
  {
    slug: 'copywriting-intern',
    title: 'Copywriting Intern',
    department: 'Creative',
    type: 'Internship (3–6 months)',
    location: 'Mumbai, Andheri East',
    about: 'We are offering a copywriting internship for aspiring writers who want to learn the craft of brand and digital copywriting. You will work alongside senior copywriters on real client projects.',
    requirements: [
      'Excellent written English',
      'Interest in advertising, branding, and digital marketing',
      'Basic understanding of social media platforms',
      'Portfolio of writing samples (academic, personal, or freelance)',
      'Currently pursuing or recently completed a degree in English, Journalism, Communications, or related field',
      'Eagerness to learn and take feedback constructively',
    ],
  },
  {
    slug: 'graphic-design-intern',
    title: 'Graphic Design Intern',
    department: 'Creative',
    type: 'Internship (3–6 months)',
    location: 'Mumbai, Andheri East',
    about: 'We are offering a graphic design internship for emerging designers who want hands-on agency experience. You will assist senior designers on brand projects, social media assets, and campaign creative.',
    requirements: [
      'Proficiency in Adobe Photoshop and Illustrator',
      'Basic understanding of typography, colour theory, and layout',
      'Portfolio demonstrating design sensibility (student work accepted)',
      'Currently pursuing or recently completed a degree in Design, Fine Arts, or related field',
      'Knowledge of Figma or Canva is a plus',
      'Eagerness to learn and work in a fast-paced environment',
    ],
  },
  {
    slug: 'digital-marketing-manager',
    title: 'Digital Marketing Manager',
    department: 'Marketing',
    type: 'Full-Time',
    location: 'Mumbai, Andheri East',
    about: 'We need a Digital Marketing Manager to lead multi-channel campaigns for our clients. You will own strategy, execution, and reporting across SEO, social media, performance marketing, and content — working directly with clients and internal teams.',
    requirements: [
      'Strong understanding of digital marketing across all channels',
      'Experience managing client relationships and campaign budgets',
      'Proficiency in analytics tools (GA4, Meta Business Suite, Google Ads)',
      'Ability to build strategy decks and present to clients',
      'Leadership skills with experience managing 2-4 person teams',
      'Minimum 5 years in digital marketing',
      'Agency experience strongly preferred',
    ],
  },
  {
    slug: 'digital-marketing-intern',
    title: 'Digital Marketing Intern',
    department: 'Marketing',
    type: 'Internship (3–6 months)',
    location: 'Mumbai, Andheri East',
    about: 'We are offering a digital marketing internship for students and fresh graduates who want to learn the full spectrum of digital marketing — from SEO and social media to paid campaigns and analytics.',
    requirements: [
      'Basic understanding of digital marketing concepts',
      'Familiarity with social media platforms (Instagram, LinkedIn, Facebook)',
      'Interest in data, analytics, and marketing technology',
      'Currently pursuing or recently completed a degree in Marketing, Business, Communications, or related field',
      'Proficiency in MS Office or Google Workspace',
      'Eagerness to learn and willingness to work across teams',
    ],
  },
];

export const careerSlugs = careers.map((c) => c.slug);
